#!/bin/bash -ex

DOCKER_ARCH=${BUILD_ARCH:-arm64v8}
DOCKER_ORG=mcharo
DOCKER_IMAGE=archlinux-${DOCKER_ARCH}

out() { printf "$1 $2\n" "${@:3}"; }
error() { out "==> ERROR:" "$@"; } >&2
die() { error "$@"; exit 1; }

# get latest Arch Linux tarball
LATEST_AMD64_URL='http://mirror.rackspace.com/archlinux/iso/latest'
LATEST_AMD64_FILENAME=$(curl -sL "${LATEST_AMD64_URL}" | grep 'tar.gz' | sed -E 's/.*href="(.*)".*/\1/g' | grep -v '.sig')
amd64="${LATEST_AMD64_URL}/${LATEST_AMD64_FILENAME}"
arm32v5='http://os.archlinuxarm.org/os/ArchLinuxARM-armv5-latest.tar.gz'
arm32v6='http://os.archlinuxarm.org/os/ArchLinuxARM-rpi-latest.tar.gz'
arm32v7='http://os.archlinuxarm.org/os/ArchLinuxARM-armv7-latest.tar.gz'
arm64v8='http://os.archlinuxarm.org/os/ArchLinuxARM-aarch64-latest.tar.gz'
LATEST_TARBALL="${!DOCKER_ARCH}"
FILENAME="${LATEST_TARBALL##*/}"
EXTRACTED_FILENAME="${FILENAME%.*}"
wget -q "${LATEST_TARBALL}"
if [[ "${DOCKER_ARCH}" = "amd64" ]]; then
  wget -q "${LATEST_AMD64_URL}/md5sums.txt"
  grep "${FILENAME}" md5sums.txt > "${FILENAME}.md5"
else
  wget -q "${LATEST_TARBALL}.md5"
fi

# verify download is valid
md5sum -c "${FILENAME}.md5" || die "Checksum failed"
gzip -d "${FILENAME}"

if [[ "${DOCKER_ARCH}" = "amd64" ]]; then
  mkdir extract
  tar xf "${EXTRACTED_FILENAME}" --strip-components=1 -C extract
  pushd extract
  tar -c . | docker import - "${DOCKER_ORG}/${DOCKER_IMAGE}:latest-base"
  popd
else
  docker import "${EXTRACTED_FILENAME}" "${DOCKER_ORG}/${DOCKER_IMAGE}:latest-base"
fi

docker build --build-arg ARCH=${DOCKER_ARCH} \
  -t $DOCKER_ORG/$DOCKER_IMAGE \
  -f Dockerfile .

docker build --build-arg ARCH=${DOCKER_ARCH} \
  -t $DOCKER_ORG/$DOCKER_IMAGE:devel \
  -f Dockerfile.devel .
