#!/bin/bash -ex

DOCKER_ARCH=${BUILD_ARCH:-amd64}
DOCKER_ORG=mcharo
DOCKER_IMAGE=archlinux

docker push $DOCKER_ORG/$DOCKER_IMAGE:${DOCKER_ARCH}
docker push $DOCKER_ORG/$DOCKER_IMAGE:${DOCKER_ARCH}-devel
